# Generated by Django 5.1.3 on 2024-11-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='imagens',
            new_name='imagem',
        ),
    ]
