# Generated by Django 5.0.2 on 2024-12-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='imagem',
        ),
        migrations.CreateModel(
            name='ReceitaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='receitas/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='Receitas.receita')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
