# Generated by Django 5.1.3 on 2024-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas', '0002_rename_imagens_receita_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
